GET http://127.0.0.1:81

###

POST http://127.0.0.1:81 HTTP/1.1
content-type: application/json

{
    "_id": 2,
    "accountID": 2,
    "userName": "John Doe",
    "titleID": 2,
    "userAction": "Paused",
    "dateTime": "2022-01-01",
    "pointOfInteraction": "01:33:10",
    "typeOfInteraction": "Stopped"
}